<?php

namespace Tests\Feature\Admin;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Auth;
use Tests\TestCase;

class AdminAuthTest extends TestCase
{
    use RefreshDatabase;
    private User $admin;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->admin = User::factory()->create([
            'isAdmin' => 1
        ]);
    }

    public function test_admin_login_page_can_be_rendered()
    {
        $response = $this->get('/admin/login');

        $response->assertStatus(200);
    }

    public function test_admin_is_redirected_to_admin_dashboard_after_successful_login()
    {
        $response = $this->post('/admin/login', [
            'email' => $this->admin->email,
            'password' => 'password'
        ]);

        $response->assertRedirect('/admin/dashboard');
    }

    public function test_admin_is_redirected_to_admin_login_page_after_unsuccessful_login()
    {
        $response = $this->post('/admin/login', [
            'email' => $this->admin->email,
            'password' => 'wrong-password'
        ]);

        $response->assertRedirect('/admin/login');
    }

    public function test_admin_is_redirected_to_admin_login_page_if_not_logged_in()
    {
        $response = $this->get('/admin/dashboard');

        $response->assertRedirect('/admin/login');
    }

    public function test_admin_is_redirected_to_home_page_after_logout()
    {
        $response = $this->actingAs($this->admin)->post('/admin/logout');

        $response->assertRedirect('/');
    }
}
