version: '3.8'

services:
    app:
        build:
            context: .
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./node_modules:/var/www/node_modules
        ports:
            - "8000:8000"
            - "5173:5173"
        depends_on:
            - database
    database:
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql

volumes:
  db_data: ~

